### ISSUE TITLE
State of Spark support?

### ISSUE THREAD

**Issue by jbauer180266** [matt-piziak/JoBimText#1]
Dear Sir or Madam,

I'm about to start working on the integration of JoBim Text into an existing QA pipeline (open source, university research) and would like to directly use Spark instead of Hadoop. I remember that Dr. Gliozzo mentioned in an IBM lecture that migrating to Spark [regarding distributional semantics] is / was also a goal of the Watson team. Unfortunately, I'm not too experienced in either Hadoop or Spark, yet.

Is it possible for me to directly target Spark or is Hadoop still my only really viable option? From a first glance at the tutorials it seems like they are still rather focused on Hadoop and also the VM that is provided seems to support Hadoop only.

Finally: Are there any special hints, starting points or other recommendations I should be aware of before I tackle this task? I currently have quite a few sources at hand including the books by Prof. Dr. Biemann and Dr. Gliozzo as well as all relevant papers, but my schedule is rather tight so I would highly appreciate any advice you can provide me with.

Thank you very much in advance.

Best wishes,
Joe

**Comment by matt-piziak** [comment]
Hello Joe,

I am not a maintainer of JoBimText; I merely took a class under Dr. Gliozzo
in college. I do not have the necessary expertise to answer your question,
but I see that you have already reached out to the maintainers on
SourceForge.

Best of luck,
Matt

**Comment by jbauer180266** [comment]
Well, thank you for your kind reply nevertheless. I must say I envy you for having been able to attend a class by Dr. Gliozzo - must have been a tremendous experience.

All the best,
Joe
